#include "\m\aais\addons\core\cfgAttributes\External.hpp"
#include "CfgAttributes\CommanderRankAttribute.hpp"
#include "CfgAttributes\CommanderPersonalityAttribute.hpp"
#include "CfgAttributes\CommanderSideAttribute.hpp"
#include "CfgAttributes\CommanderAssignModeAttribute.hpp"
#include "CfgAttributes\GroupAreaSelectAttribute.hpp"
#include "CfgAttributes\GroupAssetTypeAttribute.hpp"
