#include "\m\aais\addons\core\cfgAttributes\External.hpp"
#include "cfgAttributes\CommanderRankAttribute.hpp"
#include "cfgAttributes\CommanderPersonalityAttribute.hpp"
#include "cfgAttributes\CommanderSideAttribute.hpp"
#include "cfgAttributes\CommanderAssignModeAttribute.hpp"
#include "cfgAttributes\GroupAreaSelectAttribute.hpp"
#include "cfgAttributes\GroupAssetTypeAttribute.hpp"
