#include "cfgAttributes\External.hpp"
#include "CfgAttributes\3DEN\AIOnlyCategoryAttributes.hpp"
#include "CfgAttributes\3DEN\PlayerOnlyCategoryAttributes.hpp"
#include "CfgAttributes\3DEN\SliderAttribute.hpp"
#include "CfgAttributes\SliderTimeDay.hpp"
