PREP(helperSpawnGroup);
PREP(helperSpawnInfantry);
PREP(helperSpawnVehicle);
PREP(populateMarker);
PREP(spawnGroup);
PREP(spawnGroupFromConfig);
PREP(spawnGroupFromTemplate);
PREP(spawnGroupPFH);
PREP(spawnUnitsGroupPFH);
